refactor: :zap: update status code and server error case add
42seoulWebserv/irc pull request #55
Opened 2023-11-24 09:38 UTC by moaoh

- POST error case에 맞는 status code로 값을 변경하였습니다.
- #51 에 해당하는 server error case를 잡아내는 로직도 추가하였습니다.

2023-11-25 07:13 UTC, sindydwns requested changes
`curl` 로 `POST`요청을 했을때 `Content-Length` 가 없어 계속 기다리는 현상이 있습니다. 이를 대응하기 위해 `Content-Length`헤더를 포함하여 응답하면 좋습니다.

2023-11-25 07:13 UTC, sindydwns commented on src/processor/MethodPostProcessor.cpp
> +  }
```suggestion
  }
  client_.setResponseHeader("Content-Length", "0");
```

2023-11-25 07:15 UTC, sindydwns commented on src/processor/MethodPostProcessor.cpp
> +  client_.getDataStream().readStr(client_.getResponse().toString());
```suggestion
  }
  client_.setResponseHeader("Content-Length", "0");
  client_.getDataStream().readStr(client_.getResponse().toString());
```

2023-11-27 06:27 UTC, moaoh commented on src/processor/MethodPostProcessor.cpp
> +  client_.getDataStream().readStr(client_.getResponse().toString());
확인하여 추가완료했습니다! 확인부탁드려요

2023-11-27 06:55 UTC, sindydwns approved these changes
lgtm

2023-11-27 07:01 UTC, merged